#include<stdio.h>
static int d = 0;
int main(int argc, char *argv[]){
	int i = 0;
	int a = 0;
	int b = 0;
	int c = 0;

   	if ( argc != 2 ){
       printf("Usage: %s <count>\n", argv[0]);
       exit(5);
    }

	/*snippets of assembly code of loop generated by optimization flag -O1
	$L18:
		addu	$17,$17,$2
		addu	$18,$18,2
		addu	$17,$17,$18		//first hazard due to $17 and $18, and need 2 cycles stall due to $18
		addu	$19,$19,1
		addu	$18,$18,$17		//second hazard due to $17, need 1 cycle stall
		subu	$2,$2,1
		bgez	$2,$L18*/		//third hazard due to $2, need 2 cycle stalls

	for(i=atoi(argv[1]);i>=0;i--){
		a += i;
		b += 2;    
		a += b;
		c += 1;
		b = a+b;
	}

	printf("%d, %d, %d, %d",a, b, c, i);
	return 0; 
} 
